### ISSUE TITLE
alternative two step workflow

### ISSUE THREAD

**Issue by mr-c** [NLeSC/cwl-tutorial#2]
This was improvised on the spot, may be too complex:

make-instructions.cwl
``` yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

inputs:
  numbers:
    type: int[]
    inputBinding:
      itemSeparator: "+"

baseCommand: [ echo ]

outputs:
 response: stdout
```

bc.cwl
``` yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

inputs:
  instructions:
    type: File

stdin: $(inputs.instructions.path)

baseCommand: [ bc ]

outputs:
 result: stdout
```

cwl-workflow.cwl
``` yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

inputs:
 myNumbers:
   type: int[]

steps:
 myInstructions:
   run: make-instructions.cwl
   in:
     numbers: myNumbers
   out: [ response ]

 do-math:
   run: bc.cwl
   in:
     instructions: myInstructions/response
   out: [ result ]

outputs:
  answer:
    type: File
    outputSource: do-math/result  
```
